# Generated by Django 3.0.3 on 2020-02-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatorDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_A', models.CharField(max_length=10)),
                ('value_B', models.CharField(max_length=10)),
                ('value_C', models.CharField(max_length=10)),
            ],
        ),
    ]
