# Generated by Django 3.0.3 on 2020-02-13 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatorTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_A', models.CharField(max_length=10)),
                ('value_B', models.CharField(max_length=10)),
                ('value_C', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ClassTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xq', models.CharField(max_length=20)),
                ('kh', models.CharField(max_length=20)),
                ('sksj', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeTable',
            fields=[
                ('yxh', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('mc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherTable',
            fields=[
                ('gh', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('xm', models.CharField(max_length=10)),
                ('xl', models.CharField(max_length=10)),
                ('yxh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myWEB.CollegeTable')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTable',
            fields=[
                ('xh', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('xm', models.CharField(max_length=10)),
                ('yydj', models.CharField(max_length=10)),
                ('yxh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myWEB.CollegeTable')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xq', models.CharField(max_length=20)),
                ('pscj', models.FloatField()),
                ('kscj', models.FloatField()),
                ('zpcj', models.FloatField()),
                ('gh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myWEB.TeacherTable')),
                ('kh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myWEB.ClassTable')),
                ('xh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myWEB.StudentTable')),
            ],
        ),
        migrations.AddField(
            model_name='classtable',
            name='gh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myWEB.TeacherTable'),
        ),
    ]
