# Generated by Django 3.0.3 on 2020-02-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWEB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtable',
            name='km',
            field=models.CharField(default='数据结构', max_length=20),
            preserve_default=False,
        ),
    ]
