# Generated by Django 3.0.3 on 2020-02-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWEB', '0002_classtable_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoretable',
            name='kscj',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='scoretable',
            name='pscj',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='scoretable',
            name='zpcj',
            field=models.FloatField(blank=True),
        ),
    ]
